# Streamlit Secrets Configuration
# Add your Hugging Face API token and model configurations here
# Uncomment and fill in the values below:

# HF_TOKEN = "your_huggingface_token_here"
# HF_MODEL_IMAGE = "Salesforce/blip2-flan-t5-xl"
# HF_MODEL_ASR = "openai/whisper-large-v2"

# Note: The app will work without this file using default models
# To use Hugging Face models, get a token from: https://huggingface.co/settings/tokens
