# Streamlit Secrets Template
# This file is a template - DO NOT commit actual secrets to version control!
# 
# For local development, add your secrets here:
# GOOGLE_API_KEY = "your_google_api_key_here"
#
# For Streamlit Cloud deployment:
# 1. Go to your app settings in Streamlit Cloud dashboard
# 2. Click "Secrets" tab  
# 3. Add: GOOGLE_API_KEY = "your_actual_key_here"
#
# The app will automatically use Streamlit Cloud secrets when deployed